# Generated by Django 5.0.4 on 2024-04-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='resume_collet',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
