# Generated by Django 5.0.4 on 2024-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='motivation_desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
