# Generated by Django 5.0.4 on 2024-04-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancy_resume_collet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='resume_collet',
            new_name='resume_collect',
        ),
    ]
